//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARPrj.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlinesTicketsType
    {
        public int Id { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public Nullable<int> AirlineId { get; set; }
        public Nullable<int> TicketsTypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual TicketsType TicketsType { get; set; }
    }
}
